/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Governable, GovernableInterface } from "../Governable";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousGovernor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "GovernorPulled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousGovernor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "GovernorPushed",
    type: "event",
  },
  {
    inputs: [],
    name: "governor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pullGovernor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newGovernor_",
        type: "address",
      },
    ],
    name: "pushGovernor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceGovernor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b0319163390811782556040519091907fffd6fed33fe8ec1016718bdd5d04ae6fecd9aba0da6578807daaaa7fc3d16826908290a36103658061005f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630c340a24146100515780631f5f2ccc14610070578063d8a0421214610085578063e026049c1461008d575b600080fd5b600054604080516001600160a01b039092168252519081900360200190f35b61008361007e366004610328565b610095565b005b61008361016b565b61008361025c565b6000546001600160a01b031633146101035760405162461bcd60e51b815260206004820152602660248201527f476f7665726e61626c653a2063616c6c6572206973206e6f742074686520676f6044820152653b32b93737b960d11b60648201526084015b60405180910390fd5b600080546040516001600160a01b03808516939216917f4fbd6e04620907a96d194bfd18fc026ef2836202d9265ffe2d9d9a944a9d907491a36001805473ffffffffffffffffffffffffffffffffffffffff19166001600160a01b0392909216919091179055565b6001546001600160a01b031633146101eb5760405162461bcd60e51b815260206004820152602860248201527f476f7665726e61626c653a206d757374206265206e657720676f7665726e6f7260448201527f20746f2070756c6c00000000000000000000000000000000000000000000000060648201526084016100fa565b600154600080546040516001600160a01b0393841693909116917fffd6fed33fe8ec1016718bdd5d04ae6fecd9aba0da6578807daaaa7fc3d1682691a3600180546000805473ffffffffffffffffffffffffffffffffffffffff199081166001600160a01b03841617909155169055565b6000546001600160a01b031633146102c55760405162461bcd60e51b815260206004820152602660248201527f476f7665726e61626c653a2063616c6c6572206973206e6f742074686520676f6044820152653b32b93737b960d11b60648201526084016100fa565b600080546040516001600160a01b03909116907fffd6fed33fe8ec1016718bdd5d04ae6fecd9aba0da6578807daaaa7fc3d16826908390a36000805473ffffffffffffffffffffffffffffffffffffffff19908116909155600180549091169055565b60006020828403121561033a57600080fd5b81356001600160a01b038116811461035157600080fd5b939250505056fea164736f6c634300080a000a";

export class Governable__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Governable> {
    return super.deploy(overrides || {}) as Promise<Governable>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Governable {
    return super.attach(address) as Governable;
  }
  connect(signer: Signer): Governable__factory {
    return super.connect(signer) as Governable__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GovernableInterface {
    return new utils.Interface(_abi) as GovernableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Governable {
    return new Contract(address, _abi, signerOrProvider) as Governable;
  }
}
