/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAllocator, IAllocatorInterface } from "../IAllocator";

const _abi = [
  {
    inputs: [],
    name: "harvest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAllocator__factory {
  static readonly abi = _abi;
  static createInterface(): IAllocatorInterface {
    return new utils.Interface(_abi) as IAllocatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAllocator {
    return new Contract(address, _abi, signerOrProvider) as IAllocator;
  }
}
