/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IConvex, IConvexInterface } from "../IConvex";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pid",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_stake",
        type: "bool",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IConvex__factory {
  static readonly abi = _abi;
  static createInterface(): IConvexInterface {
    return new utils.Interface(_abi) as IConvexInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConvex {
    return new Contract(address, _abi, signerOrProvider) as IConvex;
  }
}
