/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICurve3Pool, ICurve3PoolInterface } from "../ICurve3Pool";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
      {
        internalType: "uint256[4]",
        name: "_deposit_amounts",
        type: "uint256[4]",
      },
      {
        internalType: "uint256",
        name: "_min_mint_amount",
        type: "uint256",
      },
    ],
    name: "add_liquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_burn_amount",
        type: "uint256",
      },
      {
        internalType: "int128",
        name: "i",
        type: "int128",
      },
      {
        internalType: "uint256",
        name: "_min_amount",
        type: "uint256",
      },
    ],
    name: "remove_liquidity_one_coin",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICurve3Pool__factory {
  static readonly abi = _abi;
  static createInterface(): ICurve3PoolInterface {
    return new utils.Interface(_abi) as ICurve3PoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICurve3Pool {
    return new Contract(address, _abi, signerOrProvider) as ICurve3Pool;
  }
}
