/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGroDepositHandler,
  IGroDepositHandlerInterface,
} from "../IGroDepositHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[3]",
        name: "inAmounts",
        type: "uint256[3]",
      },
      {
        internalType: "uint256",
        name: "minAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_referral",
        type: "address",
      },
    ],
    name: "depositPwrd",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGroDepositHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IGroDepositHandlerInterface {
    return new utils.Interface(_abi) as IGroDepositHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGroDepositHandler {
    return new Contract(address, _abi, signerOrProvider) as IGroDepositHandler;
  }
}
