/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGroWithdrawHandler,
  IGroWithdrawHandlerInterface,
} from "../IGroWithdrawHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "pwrd",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minAmount",
        type: "uint256",
      },
    ],
    name: "withdrawAllSingle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGroWithdrawHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IGroWithdrawHandlerInterface {
    return new utils.Interface(_abi) as IGroWithdrawHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGroWithdrawHandler {
    return new Contract(address, _abi, signerOrProvider) as IGroWithdrawHandler;
  }
}
