/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMigrator, IMigratorInterface } from "../IMigrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "enum IMigrator.TYPE",
        name: "_from",
        type: "uint8",
      },
      {
        internalType: "enum IMigrator.TYPE",
        name: "_to",
        type: "uint8",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMigrator__factory {
  static readonly abi = _abi;
  static createInterface(): IMigratorInterface {
    return new utils.Interface(_abi) as IMigratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMigrator {
    return new Contract(address, _abi, signerOrProvider) as IMigrator;
  }
}
