/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IOnsenAllocator,
  IOnsenAllocatorInterface,
} from "../IOnsenAllocator";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_stake",
        type: "bool",
      },
    ],
    name: "harvest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOnsenAllocator__factory {
  static readonly abi = _abi;
  static createInterface(): IOnsenAllocatorInterface {
    return new utils.Interface(_abi) as IOnsenAllocatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOnsenAllocator {
    return new Contract(address, _abi, signerOrProvider) as IOnsenAllocator;
  }
}
