/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITokemakManager,
  ITokemakManagerInterface,
} from "../ITokemakManager";

const _abi = [
  {
    inputs: [],
    name: "currentCycleIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITokemakManager__factory {
  static readonly abi = _abi;
  static createInterface(): ITokemakManagerInterface {
    return new utils.Interface(_abi) as ITokemakManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokemakManager {
    return new Contract(address, _abi, signerOrProvider) as ITokemakManager;
  }
}
