/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IveFXSYieldDistributorV4,
  IveFXSYieldDistributorV4Interface,
} from "../IveFXSYieldDistributorV4";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "checkpointOtherUser",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "earned",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getYield",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "notifyRewardAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "notifier_addr",
        type: "address",
      },
    ],
    name: "toggleRewardNotifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "yieldDuration",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IveFXSYieldDistributorV4__factory {
  static readonly abi = _abi;
  static createInterface(): IveFXSYieldDistributorV4Interface {
    return new utils.Interface(_abi) as IveFXSYieldDistributorV4Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IveFXSYieldDistributorV4 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IveFXSYieldDistributorV4;
  }
}
